projectBuilding:

  commonSettings:

    selectiveExecutions:

      Distributable:

        tasksAndSourceFilesSelection:

          ECMA_ScriptLogicProcessing: [ Distributable ]

      Tests:

        tasksAndSourceFilesSelection:

          markupProcessing: [ Tests ]
          stylesProcessing: [ Tests ]
          ECMA_ScriptLogicProcessing: [ Tests ]

        browserLiveReloadingSetupID: Tests


  # === Markup =========================================================================================================
  markupProcessing:

    entryPointsGroups:

      Tests:

        entryPointsSourceFilesTopDirectoryOrSingleFileRelativePath: Tests/Source
        partialsRecognition:
          excludeFilesWithPrefixes: "_"
          excludeSubdirectoriesWithPrefixes: "_"

        buildingModeDependent:
          DEVELOPMENT:
            outputBaseDirectoryRelativePath: Tests/Output



  # === Styles =========================================================================================================
  stylesProcessing:

    entryPointsGroups:

      Tests:

        entryPointsSourceFilesTopDirectoryOrSingleFileRelativePath: Tests/Source

        partialsRecognition:
          excludeFilesWithPrefixes: "_"
          excludeSubdirectoriesWithPrefixes: "_"

        buildingModeDependent:
          DEVELOPMENT:
            outputBaseDirectoryRelativePath: Tests/Output


  # === フロントエンド挙動制御記法事前処理 ======================================================================================
  ECMA_ScriptLogicProcessing:

    common:

      directoriesRelativePathsAliases:

        "@Source": Source
        "@SVG_Icons": Source/SVG_Icons
        "@Components": Source/Components

    entryPointsGroups:

      Tests:

        entryPointsSourceFilesTopDirectoryOrSingleFileRelativePath: Tests/Source

        partialsRecognition:
          excludeFilesWithPrefixes: "_"
          excludeSubdirectoriesWithPrefixes: "_"

        targetRuntime:
          type: BROWSER

        buildingModeDependent:
          DEVELOPMENT:
            outputBaseDirectoryRelativePath: Tests/Output


  # === Development server =============================================================================================
  browserLiveReloading:

    Tests:

      customStartingFilenameWithExtension: Tests.html
      targetFilesRootDirectoryRelativePath: Tests/Output
