projectBuilding:

  commonSettings:

    selectiveExecutions:

      Distributable:

        tasksAndSourceFilesSelection:

          ECMA_ScriptLogicProcessing: [ Distributable ]

      Tests:

        tasksAndSourceFilesSelection:

          markupProcessing: [ Tests ]
          stylesProcessing: [ Tests ]
          ECMA_ScriptLogicProcessing: [ Tests ]

        browserLiveReloadingSetupID: Tests


  # === Markup =========================================================================================================
  markupProcessing:

    common:
      buildingModeDependent:
        LOCAL_DEVELOPMENT: { mustResolveResourceReferencesToRelativePaths: true }

    entryPointsGroups:

      Tests:

        topDirectoryRelativePath: Tests/Source
        partialsRecognition:
          excludeFilesWithPrefixes: "_"
          excludeSubdirectoriesWithPrefixes: "_"

        buildingModeDependent:
          LOCAL_DEVELOPMENT:
            outputTopDirectoryRelativePath: Tests/Output



  # === Styles =========================================================================================================
  stylesProcessing:

    entryPointsGroups:

      Tests:

        topDirectoryRelativePath: Tests/Source

        partialsRecognition:
          excludeFilesWithPrefixes: "_"
          excludeSubdirectoriesWithPrefixes: "_"

        buildingModeDependent:
          LOCAL_DEVELOPMENT:
            outputTopDirectoryRelativePath: Tests/Output


  # === ECMAScript logic processing ====================================================================================
  ECMA_ScriptLogicProcessing:

    entryPointsGroups:

      Distributable:

        singleEntryPointRelativePath: Source/index.ts

        targetRuntime:
          type: BROWSER

        distributing:
          exposingOfExportsFromEntryPoints:
            mustExpose: true
          typeScriptTypesDeclarations:
            mustGenerate: true

        buildingModeDependent:

          LOCAL_DEVELOPMENT:
            outputTopDirectoryRelativePath: "Distributable"

          PRODUCTION:
            outputTopDirectoryRelativePath: "Distributable"
            revisioning: { disable: true }


      Tests:

        topDirectoryRelativePath: Tests/Source

        partialsRecognition:
          excludeFilesWithPrefixes: "_"
          excludeSubdirectoriesWithPrefixes: "_"

        targetRuntime:
          type: BROWSER

        buildingModeDependent:
          LOCAL_DEVELOPMENT:
            outputTopDirectoryRelativePath: Tests/Output


  # === Development server =============================================================================================
  browserLiveReloading:

    setups:

      Tests:

        localServer:

          rootDirectoryRelativePath: Tests/Output
          customStartingFileNameWithExtension: Tests.html

        openInBrowsers: chrome
