projectBuilding:

  commonSettings:

    selectiveExecutions:

      PugExtensions:
        tasksAndSourceFilesSelection:
          ECMA_ScriptLogicProcessing: [ PugExtensions ]

      StylesAndComponentsTesting:

        tasksAndSourceFilesSelection:
          markupProcessing: [ StylesAndComponentsTesting ]
          stylesProcessing: [ StylesAndComponentsTesting ]
          ECMA_ScriptLogicProcessing: [ ComponentsTesting ]

        browserLiveReloadingSetupID: StylesAndComponentsTesting

      StaticPreviewAnywherePage:
        tasksAndSourceFilesSelection:
          stylesProcessing: [ StaticPreviewAnywherePage ]


  # === Markup =========================================================================================================
  markupProcessing:
    entryPointsGroups:

      StylesAndComponentsTesting:
        entryPointsSourceFilesTopDirectoryOrSingleFileRelativePath: Tests
        partialsRecognition:
          excludeFilesWithPrefixes: "_"
          excludeSubdirectoriesWithPrefixes: "_"
        buildingModeDependent:
          DEVELOPMENT:
            outputBaseDirectoryRelativePath: Tests/Build


  # === Styles =========================================================================================================
  stylesProcessing:

    entryPointsGroups:

      StylesAndComponentsTesting:

        entryPointsSourceFilesTopDirectoryOrSingleFileRelativePath: Tests

        partialsRecognition:
          excludeFilesWithPrefixes: "_"
          excludeSubdirectoriesWithPrefixes: "_"
          excludeSubdirectoriesWithNames: [ "CompiledCodeCheckOnly" ]

        buildingModeDependent:
          DEVELOPMENT:
            outputBaseDirectoryRelativePath: Tests/Build

      OutputCheck:

        entryPointsSourceFilesTopDirectoryOrSingleFileRelativePath: Tests/Source/OutputCheckOnly

        buildingModeDependent:
          DEVELOPMENT:
            outputBaseDirectoryRelativePath: Tests/Build/OutputCheck


      StaticPreviewAnywherePage:

        entryPointsSourceFilesTopDirectoryOrSingleFileRelativePath: PagesTemplates/StaticPreviewAnywherePage/StaticPreviewAnywherePage.styl

        buildingModeDependent:
          DEVELOPMENT:
            outputBaseDirectoryRelativePath: PagesTemplates/StaticPreviewAnywherePage


  # === フロントエンド挙動制御記法事前処理 ======================================================================================
  ECMA_ScriptLogicProcessing:

    entryPointsGroups:

      ComponentsTesting:

        entryPointsSourceFilesTopDirectoryOrSingleFileRelativePath: Tests/Components
        targetRuntime:
          type: BROWSER

        partialsRecognition:
          excludeFilesWithPrefixes: "_"
          excludeSubdirectoriesWithPrefixes: "_"

        buildingModeDependent:
          DEVELOPMENT:
            outputBaseDirectoryRelativePath: Tests/Build/Components

      PugExtensions:

        entryPointsSourceFilesTopDirectoryOrSingleFileRelativePath: Markup/InlineECMAScript/Source/PugExtensions.ts

        targetRuntime:
          type: PUG

        distributing:
          exposingOfExportsFromEntryPoints:
            mustExpose: true
            namespace: __PUG_EXTENSIONS_EXPORTS__

        buildingModeDependent:
          PRODUCTION:
            outputBaseDirectoryRelativePath: Markup/InlineECMAScript/Temporary
            revisioning: { disable: true }


  # === Development server =============================================================================================
  browserLiveReloading:

    StylesAndComponentsTesting:

      customStartingFilenameWithExtension: Tests.html
      targetFilesRootDirectoryRelativePath: Tests/Build
