projectBuilding:

  commonSettings:

    selectiveExecutions:

      PugExtensions:
        tasksAndSourceFilesSelection:
          ECMA_ScriptLogicProcessing: [ PugExtensions ]

      Logic:
        tasksAndSourceFilesSelection:
          ECMA_ScriptLogicProcessing: [ Logic ]

      StylesAndComponentsTesting:

        tasksAndSourceFilesSelection:
          markupProcessing: [ StylesAndComponentsTesting ]
          stylesProcessing: [ StylesAndComponentsTesting ]

        browserLiveReloadingSetupID: StylesAndComponentsTesting

      StaticPreviewAnywherePage:
        tasksAndSourceFilesSelection:
          stylesProcessing: [ StaticPreviewAnywherePage ]


  # === Markup =========================================================================================================
  markupProcessing:
    entryPointsGroups:

      StylesAndComponentsTesting:
        topDirectoryRelativePath: Tests
        partialsRecognition:
          excludeFilesWithPrefixes: "_"
          excludeSubdirectoriesWithPrefixes: "_"
        buildingModeDependent:
          LOCAL_DEVELOPMENT:
            outputTopDirectoryRelativePath: Tests/Build


  # === Styles =========================================================================================================
  stylesProcessing:

    entryPointsGroups:

      StylesAndComponentsTesting:

        topDirectoryRelativePath: Tests

        partialsRecognition:
          excludeFilesWithPrefixes: "_"
          excludeSubdirectoriesWithPrefixes: "_"
          excludeSubdirectoriesWithNames: [ "CompiledCodeCheckOnly" ]

        buildingModeDependent:
          LOCAL_DEVELOPMENT:
            outputTopDirectoryRelativePath: Tests/Build

      OutputCheck:

        topDirectoryRelativePath: Tests/Source/OutputCheckOnly

        buildingModeDependent:
          LOCAL_DEVELOPMENT:
            outputTopDirectoryRelativePath: Tests/Build/OutputCheck


      StaticPreviewAnywherePage:

        singleEntryPointRelativePath: PagesTemplates/StaticPreviewAnywherePage/StaticPreviewAnywherePage.styl

        buildingModeDependent:
          LOCAL_DEVELOPMENT:
            outputTopDirectoryRelativePath: PagesTemplates/StaticPreviewAnywherePage


  # === ECMAScript logic processing ====================================================================================
  ECMA_ScriptLogicProcessing:

    entryPointsGroups:

      Logic:

        singleEntryPointRelativePath: index.ts

        targetRuntime:
          type: BROWSER

        distributing:
          exposingOfExportsFromEntryPoints:
            mustExpose: true
          typeScriptTypesDeclarations:
            mustGenerate: true

        buildingModeDependent:

          PRODUCTION:
            outputTopDirectoryRelativePath: "LogicDistributable"
            revisioning: { disable: true }


      PugExtensions:

        singleEntryPointRelativePath: Markup/InlineECMAScript/Source/PugExtensions.ts

        targetRuntime:
          type: PUG

        distributing:
          exposingOfExportsFromEntryPoints:
            mustExpose: true
            namespace: __PUG_EXTENSIONS_EXPORTS__

        buildingModeDependent:
          PRODUCTION:
            outputTopDirectoryRelativePath: Markup/InlineECMAScript/Temporary
            revisioning: { disable: true }


  # === Development server =============================================================================================
  browserLiveReloading:

    setups:

      StylesAndComponentsTesting:

        localServer:

          rootDirectoryRelativePath: Tests/Build
          customStartingFileNameWithExtension: Tests.html

        openInBrowsers: chrome
