$projectBuilding:

  $commonSettings:

    $selectiveExecutions:

      PugAuxiliaries:
        $tasksAndSourceFilesSelection:
          $ECMA_ScriptLogicProcessing: [ PugExtensions, GUI_ComponentsRequirements ]

      Logic:
        $tasksAndSourceFilesSelection:
          $ECMA_ScriptLogicProcessing: [ Logic ]

      StylesAndComponentsTesting:

        $tasksAndSourceFilesSelection:
          $markupProcessing: [ StylesAndComponentsTesting ]
          $stylesProcessing: [ StylesAndComponentsTesting ]
          $ECMA_ScriptLogicProcessing: [ StylesAndComponentsTesting ]

        $browserLiveReloadingSetupID: StylesAndComponentsTesting

      Workbenches:

        $tasksAndSourceFilesSelection:
          $markupProcessing: [ Workbenches ]
          $stylesProcessing: [ Workbenches ]
          $ECMA_ScriptLogicProcessing: [ Workbenches ]

        $browserLiveReloadingSetupID: Workbenches

      StaticPreviewAnywherePage:
        $tasksAndSourceFilesSelection:
          $stylesProcessing: [ StaticPreviewAnywherePage ]


  # ━━━ Markup Processing ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  $markupProcessing:

    $common:

      $buildingModeDependent:

        $localDevelopment:

          $mustResolveResourcesPointersToRelativePaths: true

    $entryPointsGroups:

      StylesAndComponentsTesting:
        $sourceFilesTopDirectoryRelativePath: Tests/Source
        $partialsRecognition:
          $excludeFilesWithPrefixes: "_"
          $excludeSubdirectoriesWithPrefixes: "_"
        $buildingModeDependent:
          $localDevelopment:
            $outputTopDirectoryRelativePath: Tests/Build

      Workbenches:
        $sourceFilesTopDirectoryRelativePath: Workbenches/Source
        $partialsRecognition:
          $excludeFilesWithPrefixes: "_"
          $excludeSubdirectoriesWithPrefixes: "_"
        $buildingModeDependent:
          $localDevelopment:
            $outputTopDirectoryRelativePath: Workbenches/Build


  # ━━━ Styles Processing ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  $stylesProcessing:

    $entryPointsGroups:

      StylesAndComponentsTesting:

        $sourceFilesTopDirectoryRelativePath: Tests/Source

        $partialsRecognition:
          $excludeFilesWithPrefixes: "_"
          $excludeSubdirectoriesWithPrefixes: "_"
          $excludeSubdirectoriesWithNames: [ "CompiledCodeCheckOnly" ]

        $buildingModeDependent:
          $localDevelopment:
            $outputTopDirectoryRelativePath: Tests/Build

      Workbenches:

        $sourceFilesTopDirectoryRelativePath: Workbenches/Source

        $partialsRecognition:
          $excludeFilesWithPrefixes: "_"
          $excludeSubdirectoriesWithPrefixes: "_"

        $buildingModeDependent:
          $localDevelopment:
            $outputTopDirectoryRelativePath: Workbenches/Build

      OutputCheck:

        $sourceFilesTopDirectoryRelativePath: Tests/Source/OutputCheckOnly

        $buildingModeDependent:
          $localDevelopment:
            $outputTopDirectoryRelativePath: Tests/Build/OutputCheck


      StaticPreviewAnywherePage:

        $singleEntryPointSourceFileRelativePath: PagesTemplates/StaticPreviewAnywherePage/StaticPreviewAnywherePage.styl

        $buildingModeDependent:
          $production:
            $outputTopDirectoryRelativePath: PagesTemplates/StaticPreviewAnywherePage
            $revisioning: { $disable: true }


  # ━━━ ECMAScript Logic Processing ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  $ECMA_ScriptLogicProcessing:

    $entryPointsGroups:

      Logic:

        $singleEntryPointSourceFileRelativePath: index.ts

        $targetRuntime:
          $type: BROWSER

        $distributing:
          $exposingOfExportsFromEntryPoints:
            $mustExpose: true
          $typeScriptTypesDeclarations:
            $mustGenerate: true
          $externalizingDependencies:
            - @yamato-daiwa/es-extensions
            - @yamato-daiwa/es-extensions-browserjs

        $buildingModeDependent:

          $production:
            $outputTopDirectoryRelativePath: "LogicDistributable"
            $revisioning: { $disable: true }


      PugExtensions:

        $singleEntryPointSourceFileRelativePath: Markup/InlineECMAScript/Source/PugExtensions.ts

        $targetRuntime:
          $type: PUG

        $distributing:
          $exposingOfExportsFromEntryPoints:
            $mustExpose: true
            $namespace: YDF

        $buildingModeDependent:
          $production:
            $outputTopDirectoryRelativePath: Markup/InlineECMAScript/Temporary
            $revisioning: { $disable: true }


      GUI_ComponentsRequirements:

        $singleEntryPointSourceFileRelativePath: Markup/InlineECMAScript/Source/GUI_ComponentsRequirements.ts

        $targetRuntime:
          $type: PUG

        $distributing:
          $exposingOfExportsFromEntryPoints:
            $mustExpose: true
            $namespace: __YDF_GUI_COMPONENTS_REQUIREMENTS__

        $buildingModeDependent:
          $production:
            $outputTopDirectoryRelativePath: Markup/InlineECMAScript/Temporary
            $revisioning: { $disable: true }

      StylesAndComponentsTesting:

        $sourceFilesTopDirectoryRelativePath: Tests/Source

        $targetRuntime:
          $type: BROWSER

        $partialsRecognition:
          $excludeFilesWithPrefixes: "_"
          $excludeSubdirectoriesWithPrefixes: "_"

        $buildingModeDependent:
          $localDevelopment:
            $outputTopDirectoryRelativePath: Tests/Build

      Workbenches:

        $sourceFilesTopDirectoryRelativePath: Workbenches/Source

        $targetRuntime:
          $type: BROWSER

        $partialsRecognition:
          $excludeFilesWithPrefixes: "_"
          $excludeSubdirectoriesWithPrefixes: "_"

        $buildingModeDependent:
          $localDevelopment:
            $outputTopDirectoryRelativePath: Workbenches/Build


  # ━━━ Browser Live Reloading ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  $browserLiveReloading:

    $setups:

      StylesAndComponentsTesting:

        $localServer:

          $rootDirectoryRelativePath: Tests/Build
          $customStartingFileNameWithExtension: Tests.html

        $openInBrowsers: chrome

      Workbenches:

        $localServer:

          $rootDirectoryRelativePath: Workbenches/Build
          $customStartingFileNameWithExtension: Workbenches.html

        $openInBrowsers: chrome
