extends: ./node_modules/@yamato-daiwa/style_guides/ECMAScript.js

globals:

  JSX: readonly


overrides:

  - files: [ "Source/SVG_Icons/**/*.tsx" ]
    rules:

      # The SVG attributes could be arbitrary long
      "max-len": off
